name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
            build_type: Debug
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            build_type: Debug
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
            build_type: Debug

    steps:
      - uses: actions/checkout@v4

      - name: Install CMake + Ninja
        uses: lukka/get-cmake@latest

      # install dependencies of dependencies (based on CI failures)
      - name: install dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libxi-dev libxtst-dev libxrandr-dev

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: ninja-multi-vcpkg
          buildPreset: ninja-multi-vcpkg
          testPreset: ninja-multi-vcpkg
          configurePresetAdditionalArgs: "[
            '-DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}',
            '-DCMAKE_C_COMPILER=${{ matrix.c_compiler }}',
            '-DCMAKE_BUILD_TYPE=${{ matrix.build_type }}'
          ]"

  # simplify GH settings: have one single build to be required
  build-results:
    name: Final Results
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: check for failed builds
        if: ${{ needs.build.result != 'success' }}
        run: exit 1
